server.port : 8011

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  profiles:
    active: jdbc

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

